"""Configurando filhos de padraorisco

Revision ID: 154cf72c2874
Revises: d067775c6527
Create Date: 2018-02-20 12:26:34.778493

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '154cf72c2874'
down_revision = 'd067775c6527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
