"""Configurando filhos de padraorisco

Revision ID: 66d9f966e983
Revises: 154cf72c2874
Create Date: 2018-02-20 12:28:20.321911

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '66d9f966e983'
down_revision = '154cf72c2874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametrosrisco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('padraorisco_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('padrarisco_parametros', 'bases', ['padraorisco_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametrosrisco', schema=None) as batch_op:
        batch_op.drop_constraint('padrarisco_parametros', type_='foreignkey')
        batch_op.drop_column('padraorisco_id')

    # ### end Alembic commands ###
