"""Configurando filhos de baseorigem

Revision ID: d067775c6527
Revises: 
Create Date: 2018-02-20 12:16:32.358514

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd067775c6527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.create_foreign_key('baseorigem_base', 'basesorigem', ['base_id'], ['id'])


    with op.batch_alter_table('parametrosrisco', schema=None) as batch_op:
        batch_op.drop_constraint('baseorigem_parametro', type_='foreignkey')
        batch_op.drop_column('base_id')

    with op.batch_alter_table('visoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('baseorigem_visao', 'basesorigem', ['base_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visoes', schema=None) as batch_op:
        batch_op.drop_constraint('baseorigem_visao', type_='foreignkey')
        batch_op.drop_column('base_id')

    with op.batch_alter_table('parametrosrisco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('baseorigem_parametro', 'bases', ['base_id'], ['id'])

    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.drop_constraint('baseorigem_base', type_='foreignkey')

     ### end Alembic commands ###
