"""Many to Many PadraoRisco BaseOrigem

Revision ID: 7d44388aadb8
Revises: fe901b83c992
Create Date: 2018-02-20 13:34:26.056137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d44388aadb8'
down_revision = 'fe901b83c992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    op.create_table('basesorigem_padroesrisco',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['basesorigem.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['padroesrisco.id'], )
    )
    op.drop_table('padroresrisco')
    op.drop_table('bases')
    with op.batch_alter_table('parametrosrisco', schema=None) as batch_op:
        batch_op.drop_constraint('padrarisco_parametros', type_='foreignkey')
        batch_op.create_foreign_key(None, 'padroesrisco', ['padraorisco_id'], ['id'])

    """# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametrosrisco', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('padrarisco_parametros', 'bases', ['padraorisco_id'], ['id'])

    op.create_table('bases',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    op.create_table('padroresrisco',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=20), nullable=True),
    sa.Column('base_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['basesorigem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.drop_table('basesorigem_padroesrisco')
    # ### end Alembic commands ###
